### ISSUE TITLE
'DropShadow' was not found in the UIManager

### ISSUE THREAD

**Issue by AdamSheaHewett** [hoanglam10499/react-native-drop-shadow#1]
When trying to use the component, I get the title error. I am trying to use it as an animated view. Just dropped it in place of the old animated view, and instead got this error.

Looks like you have a great project going here. Keep it up, RN needs it badly.

**Comment by AdamSheaHewett** [comment]
Oops, just need to re-sync the android gradle.

**Comment by hoanglam10499** [comment]
@AdamSheaHewett  problem been resolved?

**Comment by AdamSheaHewett** [comment]
Yes

**Comment by mnassabain** [comment]
I'm getting this issue with expo, version 43.0.2. Only happens on android

**Comment by hoanglam10499** [comment]
> I'm getting this issue with expo, version 43.0.2. Only happens on android

hi @mnassabain, expo is not supported

**Comment by astriskit** [comment]
@hoanglam10499  First, this is a nice project. Thank you.

Is it possible to be ported to expo somehow?!
