### ISSUE TITLE
Verify Release Resources : FAILED

### ISSUE THREAD

**Issue by novamaster-git** [hoanglam10499/react-native-drop-shadow#10]
> Task :react-native-drop-shadow:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-drop-shadow:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/user/.gradle/caches/transforms-3/b2197c574567c595cb9e45a5d8e1862d/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by hoanglam10499** [comment]
hi, can you run `./gradlew clean` inside the `android` directory and try the build again?

**Comment by hoanglam10499** [comment]
If possible, give me some more information about
+ package react-native version
+ `build.gradle` file inside `android`

**Comment by novamaster-git** [comment]
hi @hoanglam10499 
your suggestion not worked for me
please help
Info;
React-native version: 0.69.2

it is happening when i trying to release build my app

**Comment by hoanglam10499** [comment]
hi @novamaster-git, try update version 0.0.5 and retry
