### ISSUE TITLE
 WARN  (ADVICE) View #395 of type RCTView has a shadow set but cannot calculate shadow efficiently.

### ISSUE THREAD

**Issue by ghost** [hoanglam10499/react-native-drop-shadow#20]
Hi, Thanks a lot for this fantastic package. I hit with a warning in my React Native App, when I don't set a background color to the drop shadow component style, I get this warning. I wanted to create a reusable component and pass children inside, the background of that component can be dynamic. 

`background:"transparent"` does not work as well.

` WARN  (ADVICE) View #395 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a background color to fix this, or apply the shadow to a more specific component.`

**Comment by nriccar** [comment]
bump

**Comment by EslamDarwish** [comment]
Check this comment, it solves the problem for me 
https://github.com/hoanglam10499/react-native-drop-shadow/issues/22#issuecomment-1656544268

**Comment by hoanglam10499** [comment]
hi try version 0.0.8
