### ISSUE TITLE
requireNativeComponent: "DropShadow" was not found in the UIManager.

### ISSUE THREAD

**Issue by Federico-Mameli01** [hoanglam10499/react-native-drop-shadow#21]
Can't solve this issue. I installed it through npm, my project is running with Expo and I imported the component with:
`import DropShadow from "react-native-drop-shadow";`
Has anyone else had this problem before?
Any help would be much appreciated. Thanks.

**Comment by mickaelcornelli** [comment]
Same problem. Working fine on IOS.
But got render error on Android.
"RequireNativeComponent : "DropShadow" was not found in UIManager

I'm using :
 "expo": "~45.0.0",
"react-native": "0.68.2",
"react-native-drop-shadow": "^0.0.6",

**Comment by nikitaSazhinov** [comment]
Same issue here, anybody found a solution?

**Comment by hoanglam10499** [comment]
hi @Federico-Mameli01, expo is not supported
#1
