### ISSUE TITLE
Error: "DropShadow" was not found in the UIManager

### ISSUE THREAD

**Issue by unstopp** [hoanglam10499/react-native-drop-shadow#26]
Hello,

I am  getting this error on Android. Any clues?
**requireNativeComponent: "DropShadow" was not found in the UIManager.**

Any help is very much appreciated, thank you!

**Comment by jpbast** [comment]
Same here

**Comment by unstopp** [comment]
Any news on this?

**Comment by hyoretsu** [comment]
@hoanglam10499 Also got this, really wanting to use your lib.

**Comment by PineAppleGrits** [comment]
+1

**Comment by nonotnoah** [comment]
I'm also having this issue. I tried installing older versions of this package, but I get the same issue.

**Comment by PineAppleGrits** [comment]
I solved the issue by (in my case) building the development build with expo. 
I think the thing was that it needed to implement the native code to make this work

**Comment by unstopp** [comment]
> I solved the issue by (in my case) building the development build with expo. I think the thing was that it needed to implement the native code to make this work

I'm using expo as well. Can you tell us how exactly?

**Comment by nonotnoah** [comment]
@PineAppleGrits 
> I solved the issue by (in my case) building the development build with expo. I think the thing was that it needed to implement the native code to make this work

I gave [this](https://docs.expo.dev/develop/development-builds/create-a-build/) a try, but I couldn't get it to work. I'm sure I could figure it out, but it takes almost 10 minutes to build and run my app which very inconvenient if I'm just trying to quickly see what a drop shadow looks like on a component. 

Was this the method you're talking about?

**Comment by PineAppleGrits** [comment]
I think the solution could be installing the package via npx expo install and then building the development build, have y'all tried that? At least that's what worked for me

**Comment by xml12333** [comment]
Same problem on physical android device, with expo dev.

**Comment by hoanglam10499** [comment]
hi, try version 0.0.8
=>  Expo is not supported

**Comment by Fardin96** [comment]
> hi, try version 0.0.8 => Expo is not supported

Didn't work in my case. not using expo btw.

**Comment by Fardin96** [comment]
The following solution works in my case!

https://github.com/hoanglam10499/react-native-drop-shadow/issues/1#issuecomment-659589521

just need to re-sync the android gradle using

```
cd android && ./gradlew clean
``` 

and then build.

**Comment by willnaoosmith** [comment]
If someone comes to this error again and this doesn't work:
> ```
> cd android && ./gradlew clean
> ```

Add this top your `android/settings.gradle` file:

```
include ':react-native-shadow'
project(':react-native-shadow').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/shadow/android')
```
Then re-run `react-native run-android`
