### ISSUE TITLE
DropShadow is not fabric compatible yet

### ISSUE THREAD

**Issue by sauravgk** [hoanglam10499/react-native-drop-shadow#27]
Hi,

I am using the latest version of react-native-dropshadow(0.0.7) with react-native 0.71.11 on new arch.

On running my app it displays the above error "DropShadow is not fabric compatible yet" 

Any fix for this in the pipeline or is there a patch I can consume?

![Screenshot_2023-08-17-15-17-50-63_d206cc2b66b1a80b66121147e07ea2c7](https://github.com/hoanglam10499/react-native-drop-shadow/assets/136432763/eb694e52-8e76-4640-9207-79e35e5465b4)

**Comment by hoanglam10499** [comment]
Solved 0.0.8
