### ISSUE TITLE
react-native-drop-shadow not working after update from 0.0.7 to 0.0.9

### ISSUE THREAD

**Issue by thalmann-christof** [hoanglam10499/react-native-drop-shadow#32]
We were running `react-native-drop-shadow` on 0.0.7, and it worked fine for us. After updating to 0.0.9, it does not show the shadow anymore. There is no error or warning. It just does not display it anymore. 

Do we miss anything we need to change in the implementation in that version update? Were there any breaking changes? 

We are running on:
- react-native 0.71.14
- expo 48.0.21
- android sdk target is 33

Happy for any input to get the new version running! Thanks.

**Comment by hoanglam10499** [comment]
Hi @thalmann-christof, try update new version 1.0.0

**Comment by thalmann-christof** [comment]
Thanks @hoanglam10499! It works again for us.
