### ISSUE TITLE
General error during semantic analysis: Unsupported class file major version 61

### ISSUE THREAD

**Issue by trickyc0d3r** [hoanglam10499/react-native-drop-shadow#4]
HI! 
Trying to use library within android project, which is setuped for supporting android 12 and java 11.
But When I'm trying to build an app - got every time this issue ->>>

`* What went wrong:
A problem occurred evaluating project ':react-native-drop-shadow'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-drop-shadow'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org`

**Comment by hoanglam10499** [comment]
resolve 0.0.4
