### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name DropShadow

### ISSUE THREAD

**Issue by Dimous** [hoanglam10499/react-native-drop-shadow#6]
Hello!
I updated DropShadow to 0.0.3 and application stopped working with error in subject.

| Library                         | Version |
| ------------------------------- | ------- |
| react            | beta   |
| react-native            | ^0.66.4   |
| react-native-drop-shadow   | ^0.0.3   |

Hermes enabled.

**Comment by hoanglam10499** [comment]
hi @Dimous, thank you for reporting to me.
Try again with version 0.0.4
