### ISSUE TITLE
borderRadius is not supported for Android?

### ISSUE THREAD

**Issue by indapublic** [hoanglam10499/react-native-drop-shadow#7]
```
import DropShadow from "react-native-drop-shadow";

<DropShadow
	style={{
		backgroundColor: "red",
		borderRadius: 30,
		padding: 30,
	}}
>
	<View>
		<Text>DropShadow</Text>
	</View>
</DropShadow>
```

Android:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/856260/148468980-8a3c258a-a4bc-496f-b58b-9625eb12288b.png">

iOS:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/856260/148468963-f6c80308-8208-4a3d-bf48-06fb712dcaba.png">

**Comment by indapublic** [comment]
iOS screenshot for same block:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/856260/148401492-a779a9fc-3ed6-4b42-97ba-ffea91ab77bc.png">

**Comment by hoanglam10499** [comment]
hi, try my way, it works fine
![image](https://user-images.githubusercontent.com/37326429/173595993-d3049c37-ce9e-48cb-8b09-6cf8f53a8242.png)
