### ISSUE TITLE
Invariant Violation: requireNativeComponent: "DropShadow" was not found in the UIManager.

### ISSUE THREAD

**Issue by richard7463** [hoanglam10499/react-native-drop-shadow#9]
just normally import and use

**Comment by richard7463** [comment]
react-navite version:     "react-native": "^0.66.4",

**Comment by hoanglam10499** [comment]
#1 problem been resolved

**Comment by richard7463** [comment]
> #1 resolve

sorry, I'm running it in a expo project, it can be running in emulator devices by myself, but somehow got above error.
I notice that in #1 the comment that you have mentioned this component cannot be running in an expo project ?

**Comment by hoanglam10499** [comment]
yes, expo is not supported

**Comment by richard7463** [comment]
> yes, expo is not supported

sorry, but for me that is confused, I can run it in ios and android in both emulator devices.

**Comment by AroliSG** [comment]
any solution for expo?
